export enum QueryKeys {
  LIST_FRANCHISES = "listFranchises",
  INACTIVATE_FRANCHISE = "inactivateFranchise",
  ACTIVATE_FRANCHISE = "activateFranchise",
  CREATE_FRANCHISE = "createFranchise",
  UPDATE_FRANCHISE = "updateFranchise",
  LIST_PROMOTERS = "listPromoters",
  INACTIVATE_PROMOTER = "inactivatePromoter",
  ACTIVATE_PROMOTER = "activatePromoter",
  CREATE_PROMOTER = "createPromoter",
  UPDATE_PROMOTER = "updatePromoter",
  LIST_TERMINALS = "listTerminals",
  GET_TERMINAL_TOTALS = "getTerminalTotals",
  ACTIVATE_TERMINAL = "activateTerminal",
  INACTIVATE_TERMINAL = "inactivateTerminal",
  APPROVE_TERMINALS = "approveTerminals",
  REPROVE_TERMINAL = "reproveTerminals",
  PENDING_NUMBER = "pendingNumber",
  LIST_PENDING_TERMINALS = "listPendingTerminals",
}
