/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthPromotersIndexImport } from './routes/_auth/promoters/index'
import { Route as AuthFranchisesIndexImport } from './routes/_auth/franchises/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthPromotersIndexRoute = AuthPromotersIndexImport.update({
  path: '/promoters/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthFranchisesIndexRoute = AuthFranchisesIndexImport.update({
  path: '/franchises/',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/franchises/': {
      id: '/_auth/franchises/'
      path: '/franchises'
      fullPath: '/franchises'
      preLoaderRoute: typeof AuthFranchisesIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/promoters/': {
      id: '/_auth/promoters/'
      path: '/promoters'
      fullPath: '/promoters'
      preLoaderRoute: typeof AuthPromotersIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AuthRoute: AuthRoute.addChildren({
    AuthFranchisesIndexRoute,
    AuthPromotersIndexRoute,
  }),
  LoginIndexRoute,
})

/* prettier-ignore-end */
